bigBuck.templates = {
  hunter: [
    '<div class="col-3 hunter">',
      '<div class="photo-box">',
        '<img src="<%= image %>" alt="<%= name %> Image" class="hunterImg" data-id="<%= name %>"/>',
      '</div>',
      '<ul>',
        '<li><h2><%= name %></h2></li>',
        '<li>Accuracy: <span><%= accuracy %></span></li>',
        '<li>Tolerance: <span><%= tolerance %></span></li>',
      '</ul>',
    '</div>',
  ].join(''),
  weapon: [
    '<div class="col-3 weapon">',
      '<div class="photo-box">',
        '<img src="<%= image %>" alt="<%= name %> Image" class="weaponImg" data-id="<%= name %>"/>',
      '</div>',
      '<ul>',
        '<li><h2><%= name %></h2></li>',
        '<li>Accuracy: <span><%= accuracy %></span></li>',
        '<li>Power: <span><%= power %></span></li>',
      '</ul>',
    '</div>',
  ].join(''),
  map: [
    '<div class="col-3 map">',
      '<div class="photo-box map-box" data-id="<%= image %>" style="background-image: url(<%= image %>)">',
        // '<img src="<%= image %>" alt="<%= name %> Image" class="mapImg" data-id="<%= image %>"/>',
      '</div>',
      '<ul>',
        '<li><h2><%= name %></h2></li>',
        '<li>Trophy: <span><%= trophy %></span></li>',
      '</ul>',
    '</div>',
  ].join(''),
  critter: [
    '<div class="critter-box" style="width:<%= size %>px; top:<%= top %>%; left:<%= left %>%;" data-id=<%= id %> data-pts=<%= points %>>',
      '<img src="<%= image %>" alt="<%= name %> Image" />',
    '</div>',
  ].join(''),
};
